language: ruby
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: QAeF9B+Bqsuk2T5MIZWd1qdWsS9Z6tIGlD83yhzs2YLJVcGiUZpPFQutbyW1FWz/8ItsM4NIHYstiT92+igRW7AKCuT80pg+LmLw3DY8raS+fHwxhqfSA2E3NHZjplNcsVYHEZSuySF4jLgYcXROq3RptXjdNBqmejBu2q1kEbXsF+tS7xx60sxGkJl0Nu+sGXUkMh351YGQWc1BIz7y9pPliTHyjxzCvKQaRo4SbQqB9VZRJLt5/mos+tgIwtHCPbJ+EPlGKvmtBsF+D4BHNrBvsFRik10V8K07EiXuWb2Q1mfBtA9OodBp+cevVv1k95Fzlddqp39k48TnWkCZIy/QAAf8qI4mieLcJo1AQXG1PsLw9P+FZv4QlncBwOJYHt/lQ1gHdRF9DQkHdttCGmtG7wgO9iNKZa9A5VVCHhf6rsadq1+QbVW+113PjpzOS2lXv7DHDz9rnzrD2YUarXc0H+RwBOJdXFuWuiWGqW5nY+zjqKxycw9k2u3ZlbGo79YIBKGFLVurPbT3vt76B4D/B/j2uVhTHO+0d0mU5M5sO4iSsmpdE1bC7CdDYJYXzKTKQ24ruTKFypWBYJ9FMF6m092sty+ekShwCw2er+nZgCkGwVJlhqXVKV2NgpBpbrqt097ptmKviYf1L5Y7N6SuNUx+2L6Pft+vMf5ZggY=
  app: krk-18-vader
  run: rake db:migrate
  on:
    repo: netguru-code-college/krk-18-vader
env:
  secure: zgu+ANz2gfbHK6JUd0SKB8qbNqQZ0yv6vuiNzaOqeSR6tXobP7D/Uk9jRKQpBC1CJlIoq9/KyTOSWR7XcfccEh8BimfDtzuBsQu/DqkP4F1L3u6zyQUXegqKgN9hag/fPBFAMrWV1E664ZVuRoyZQp5+BYXgV1YzF2QQFNIjXAeGwM/lRKs23Iw92gOvi2twY2FYQusUpn8N3/p87cGhdkqV9XoTgGx/8KRcw8ZUexgZo4FHzc9ma8qH+1MKNS9K0M9WwdOzIs9RxPb6tFyH1YXX/ToMyUxiFRHN/5vNfBzeOcKB3hptn3wHhCUgJieWmWBieEErkRVN3JUshdfsikwPEO/oVsdYIJV8+yrRsQ5mLRzSmQ/MqOs7DrHgq3uddIy3rg+dirGzf4cVzOy9lSCiltqQO5CSquDTy68dRCe2S50pcx3iYz9ZDhUPwYlBPMceAwVGosBYthX3fVMuwihaXo92l/80NE2u7h0P5xFAM9tMXLWmDKiUT+moJpKn2fsDW1/+OPcYLPudBt/lHlyoiAV+8b+XBj92/hjhgG2FnB2VvTVgHgsPH20lj1loBmPN/eSIElKYRlndnxScrilWdBTJVApWrzm53jFRKchg3f2atb4A66SIljFkjRWNbiGZiY9eiq0eogpgh2xUQqEIBEQf6bgemjPaoKdmIa8=
